# Spine switches
[spines]
spine1 ansible_host=192.168.200.5
spine2 ansible_host=192.168.200.10

# Leaf switches
[leafs]
leaf1 ansible_host=192.168.200.8
leaf2 ansible_host=192.168.200.7
leaf3 ansible_host=192.168.200.9
leaf4 ansible_host=192.168.200.4

# All switches (spines + leafs)
[switches:children]
spines
leafs

[switches:vars]
ansible_user=cumulus
ansible_password=!Q2w3e4r
ansible_ssh_common_args=-o StrictHostKeyChecking=no
ansible_become=false



# Servers
[servers]
server1 ansible_host=192.168.200.3
server2 ansible_host=192.168.200.6

[servers:vars]
server_bond_gateway=192.168.1.254
ansible_user=ubuntu
ansible_password=nvidia
ansible_ssh_common_args=-o StrictHostKeyChecking=no
